sudo: false
branches:
  only:
  - master
language: node_js
notifications:
  email:
    on_success: always
    on_failure: change
node_js:
  - '8'
install:
  - npm install -g codecov
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run build
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
