sudo: false
branches:
  only:
  - master
language: node_js
notifications:
  email:
    on_success: always
    on_failure: change

cache:
  directories:
    - node_modules
node_js:
  - '6'
install:
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run build
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - cd dist
  - npx semantic-release
deploy:
  provider: npm
  email: craigp@codehq.co.za
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
