sudo: false
language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
node_js:
  - '6'
  - '5'
  - '4'
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run coveralls
