sudo: false
branches:
  only:
  - master
language: node_js
notifications:
  email:
    on_success: always
    on_failure: change
cache:
  directories:
    - node_modules
node_js:
  - '9'
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
after_success:
  - npm run build
  # - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
  - npm run publish:docs
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
