sudo: false
language: node_js
notifications:
  email:
    on_success: always
    on_failure: change
node_js:
  - '8'
install:
  - npm install -g yarn
  - npm install -g codecov
  - yarn
script:
  - npm run lint
  - npm run test:cover
after_success:
  - npm run coveralls
  - bash <(curl -s https://codecov.io/bash)
